batch_size: 32
data_sayan: false
epochs: 100
initial_lr: 0.001
loss: DiceBCELoss
lr_schedule: false
momentum: 0.9
optimizer:
  params:
    dampening: 0
    lr: 0.001
    momentum: 0.9
    nesterov: true
    weight_decay: 0
  type: SGD
train_mask_threshold: 0.5
train_set: undistorted
val_batch_size: 77
val_set: downsized_cropped
