batch_size: 32
epochs: 200
initial_lr: 0.001
loss: DiceBCELoss
lr_schedule:
  gamma: 0.1
  milestones:
  - 20
optimizer:
  params:
    amsgrad: false
    betas: !!python/tuple
    - 0.9
    - 0.999
    eps: 1.0e-08
    lr: 0.001
    weight_decay: 0
  type: Adam
thresh_train_masks: true
