batch_size: 32
epochs: 100
initial_lr: 0.0001
loss: DiceBCELoss
lr_schedule:
  gamma: 0.1
  milestones:
  - 20
  - 40
  - 60
  - 80
optimizer:
  params:
    dampening: 0
    lr: 0.0001
    momentum: 0.9
    nesterov: true
    weight_decay: 0
  type: SGD
thresh_train_masks: true
