batch_size: 32
epochs: 300
initial_lr: 0.001
loss: DiceBCELoss
lr_schedule:
  gamma: 0.1
  milestones: []
optimizer:
  params:
    dampening: 0
    initial_lr: 0.001
    lr: 0.001
    momentum: 0.99
    nesterov: true
    weight_decay: 0
  type: SGD
