batch_size: 32
data_sayan: false
epochs: 300
initial_lr: 0.0001
loss: DiceBCELoss
lr_schedule:
  gamma: 0.1
  milestones:
  - 4
  - 15
optimizer:
  params:
    amsgrad: false
    betas: !!python/tuple
    - 0.9
    - 0.999
    eps: 1.0e-08
    lr: 0.0001
    weight_decay: 0
  type: Adam
slurm_id: 4890606
train_mask_threshold: 0.5
train_set: undistorted
val_batch_size: 77
val_set: downsized_cropped
