batch_size: 32
epochs: 200
initial_lr: 0.001
loss: DiceBCELoss
lr_schedule:
  gamma: 0.1
  milestones:
  - 20
optimizer:
  params:
    dampening: 0
    lr: 0.001
    momentum: 0.9
    nesterov: true
    weight_decay: 0
  type: SGD
thresh_train_masks: true
